name: Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  dist_linux:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: |
          shards build --production --release --no-debug
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_type == 'tag'
        with:
          files: |
            ./bin/untun
          make_latest: true
